'use client'
import Section from "@/components/Section";
import { useSelector } from "react-redux";
import { motion, useScroll } from "framer-motion";

//  export const metadata = {
//    title: "Portfolio Site",
//    description: "Generated by create next app",
// };

export default function Home() {
  const theme = useSelector(state => state.portfolio.theme)
  const { scrollYProgress } = useScroll();
  return (
    <main className={`h-[4000px] ${theme} transition-all duration-500`}>
       <motion.div
        className="progress"
        style={{ scaleX: scrollYProgress }}
      />
      <Section/>
    </main>
  );
}
