
 export const metadata = {
   title: "Portfolio Site",
   description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="">
      <h1>Erkan Mustafa</h1>
    </main>
  );
}
